CATEGORIES = [
    "abbreviations",
    "brands & companies",
    "childish",
    "conserved english",
    "cuisine",
    "cultural",
    "drinks",
    "education",
    "games",
    "insults",
    "kueh",
    "locations",
    "meme-derived",
    "nature",
    "ns",
    "online slang",
    "onomatopoeia",
    "particles",
    "rhyming slang",
    "sayings",
    "snowclones",
    "terms of address",
    "units of measure",
    "vulgar",
]
CERTAINTY_LEVELS = ["likely", "poss", "dubious", "warn"]
