fix = true
line-length = 80

[lint]
select = ["ALL"]
preview = true
ignore = [
"COM812",  # already handled by formatter
"CPY001",
"D100",
"D101",
"D102",
"D103",
"D104",
"D107",
"D203",
"D212",
"EM101",
"FIX002",
"PLC1901",
"S101",
"TD002",
"TD003",
"TRY003",
]

[lint.per-file-ignores]
"tests/**/test_*.py" = ["E501"]  # expecttest is used, so this line too long is ok

[lint.pep8-naming]
# names loaned from JSON can violate the rule
ignore-names = [
"*etyLit*",
"*etyNotes*",
"*etyPath*",
"*etyRoman*",
"*etyScheme*",
"*etyScript*",
"*etyTrad*",
"*etyType*",
"*exampleSource*",
"*trieId*",
"*formsClean*",
]
